---
name: gobra-nightly

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: read

jobs:
  verify:
    name: verify-gobra
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Verify the Gobra proof
        run: make verify-gobra
