---
name: gobra-nightly

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: read

jobs:
  verify:
    name: verify-gobra
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Verify the Gobra proof
        run: make verify-gobra
